<%@ Page Language="C#" AutoEventWireup="true"  MasterPageFile="~/Site.Master"  CodeBehind="Chat.aspx.cs" Inherits="FirstPlaySignalR.Chat" %>


<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h1>聊天室</h1>
    <div class="container">
        <input type="text" id="message" />
        <input type="button" id="sendmessage" value="Send" />
        <input type="hidden" id="displayname" />
        <ul id="discussion">
        </ul>
    </div>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-3.3.1.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.4.1.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">
        $(function () {
            // 声明一个代理来引用集线器。
            var chat = $.connection.chatHub;
            // 创建集线器可以调用来广播消息的函数。
            chat.client.broadcastMessage = function (name, message) {
                // Html编码显示名称和消息。
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // 添加消息到页面. 
                $('#discussion').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };
            // 设置聊天名称.
            $('#displayname').val(prompt('请输入你的名称:', ''));
            // Set initial focus to message input box.  
            $('#message').focus();
            // 开启连接.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // 调用发送消息
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment. 
                    $('#message').val('').focus();
                });
            });
        });
    </script>
</asp:Content>
